[package]
name = "pmrpc"
version = "0.1.0"
edition = "2021"
authors = ["Nigel Baillie <nigel@baillie.dev>"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
